os:
  - linux
  - osx
language: node_js
node_js:
    - "6"
    - "4"
install:
    - npm install
script:
    - npm run test
after_success:
    - npm run codecov
branches:
  only:
    - develop
matrix:
  allow_failures:
    - os: osx